### ISSUE TITLE
mobile video unavailable

### ISSUE THREAD

**Issue by ddaaggeett** [ddaaggeett/xyz#1]
web app works fine considering it doesn't use the npm package: react-native-youtube-iframe

error occurs for mobile only

**Comment by ddaaggeett** [comment]
Testing with Expo v40 AND v42

I've been using [a copy of the package](https://github.com/ddaaggeett/clipper/tree/main/src/app/components/react-native-youtube-iframe) in my source code instead of relying on the NPM module. I contributed an update dealing with an unimportant feature I required at the time of development. That feature was not included in the package until version 2, So I've just kept the copy I needed for the unimportant feature.

Now, [this error](https://github.com/LonelyCpp/react-native-youtube-iframe/issues/167) has occurred and [is easily fixed](https://github.com/LonelyCpp/react-native-youtube-iframe/issues/167#issuecomment-884702307) with an updated NPM module to version ^2.1.1 or ^1.4.2 (although I only find 1.4.1 latest).

So,

`rm -rf node_modules`<br />
`npm install react-native-youtube-iframe@2.1.1`<br />
`npm install`<br />
`import YoutubePlayer from "react-native-youtube-iframe"` (instead of the embedded copy at ...`"./react-native-youtube-iframe"`)<br />
FAIL<br />
retry for version `...@1.4.2`<br />
FAIL<br />

**Comment by LonelyCpp** [comment]
@ddaaggeett can you try replacing 
- this file : https://github.com/ddaaggeett/clipper/blob/main/src/app/components/react-native-youtube-iframe/src/PlayerScripts.js 
- with this one : https://github.com/LonelyCpp/react-native-youtube-iframe/blob/fbc119e7cbf967a016a3212e6d6f46785bc19092/src/PlayerScripts.js

If that does not work, what YouTube ID are you trying this on?

**Comment by ddaaggeett** [comment]
That hasn't worked yet.
Using any and all YouTube IDs.
